language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer
        - $HOME/bin

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-interaction --no-progress"
        - COLLECT_COVERAGE=0
        - COMPOSER_FLAGS=""

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
    include:
        -
            stage: Static Code Analysis
            php: 7.2
            env: COMPOSER_FLAGS="--no-dev --prefer-stable"
            install:
                - travis_retry composer global require $DEFAULT_COMPOSER_FLAGS phpstan/phpstan
                - composer info -D | sort
            script:
                - $HOME/.composer/vendor/bin/phpstan analyse -l 7 src/ functions.php

        - &STANDARD_TEST_JOB
            stage: Fast Test
            php: 7.0
            install:
                - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
                - composer info -D | sort
            script:
                - vendor/bin/phpunit || travis_terminate 1
                - php-cs-fixer --diff --dry-run -v fix

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 5.5
            env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 5.6

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.1

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.2

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.2
            env: COLLECT_COVERAGE=1
            before_install:
                - phpdbg --version 2> /dev/null || { echo 'No phpdbg'; export COLLECT_COVERAGE=0; }
                - if [ $COLLECT_COVERAGE == 0 ]; then travis_terminate 0; fi
                - phpenv config-rm xdebug.ini || return 0
                - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
            script:
                - phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml || travis_terminate 1
                - php vendor/bin/php-coveralls -v

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: nightly
            env: COMPOSER_FLAGS="--ignore-platform-reqs"

allow_failures:
    - php: nightly
    - env: COLLECT_COVERAGE=1
