version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tmpfs:
      - /app/vendor:uid=1000,gid=1000,exec
    volumes:
      - ./:/app
    working_dir: /app/
